#!/bin/bash

# get current wifi device
CURRENT_DEVICE=$(networksetup -listallhardwareports | awk '$3=="Wi-Fi" {getline; print $2}')
WIFI_STATUS=$(networksetup -getairportpower $CURRENT_DEVICE)

echo 

if echo "$WIFI_STATUS" | grep On
then
    # turn off wifi
   networksetup -setairportpower $CURRENT_DEVICE off
   echo "wifi:  OFF"
else
    # turn on wifi
   networksetup -setairportpower $CURRENT_DEVICE on
    echo "wifi:  ON"
fi


